from sqlalchemy import inspect, text

from app import models  # noqa: F401
from app.database import Base, engine


def main():
    Base.metadata.create_all(bind=engine)

    inspector = inspect(engine)
    if "horarios_generados" not in inspector.get_table_names():
        print("La tabla horarios_generados no existe. Se creo con el esquema actual.")
        return

    columnas = {columna["name"] for columna in inspector.get_columns("horarios_generados")}
    columnas_normalizadas = {"materia_id", "docente_id", "aula_id", "grupo_id"}

    if columnas_normalizadas.issubset(columnas):
        print("La tabla horarios_generados ya esta normalizada.")
        return

    with engine.begin() as conn:
        conn.execute(text("DROP TABLE IF EXISTS horarios_generados_new"))
        conn.execute(
            text(
                """
                CREATE TABLE horarios_generados_new (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    materia_id INTEGER NOT NULL REFERENCES materias(id),
                    docente_id INTEGER NOT NULL REFERENCES docentes(id),
                    aula_id INTEGER NOT NULL REFERENCES aulas(id),
                    grupo_id INTEGER NOT NULL REFERENCES grupos(id),
                    semestre INTEGER NOT NULL,
                    dia VARCHAR NOT NULL,
                    bloque VARCHAR NOT NULL,
                    tipo VARCHAR NOT NULL
                )
                """
            )
        )

        if {"materia", "sigla", "docente", "aula", "grupo"}.issubset(columnas):
            conn.execute(
                text(
                    """
                    INSERT INTO horarios_generados_new (
                        materia_id, docente_id, aula_id, grupo_id, semestre, dia, bloque, tipo
                    )
                    SELECT
                        m.id,
                        d.id,
                        a.id,
                        g.id,
                        h.semestre,
                        h.dia,
                        h.bloque,
                        h.tipo
                    FROM horarios_generados h
                    JOIN materias m
                        ON m.nombre = h.materia
                       AND m.sigla = h.sigla
                    JOIN docentes d
                        ON d.nombre = h.docente
                    JOIN aulas a
                        ON a.nombre = h.aula
                    JOIN grupos g
                        ON g.nombre = h.grupo
                    """
                )
            )

        conn.execute(text("DROP TABLE horarios_generados"))
        conn.execute(text("ALTER TABLE horarios_generados_new RENAME TO horarios_generados"))
        conn.execute(text("CREATE INDEX ix_horarios_generados_materia_id ON horarios_generados (materia_id)"))
        conn.execute(text("CREATE INDEX ix_horarios_generados_docente_id ON horarios_generados (docente_id)"))
        conn.execute(text("CREATE INDEX ix_horarios_generados_aula_id ON horarios_generados (aula_id)"))
        conn.execute(text("CREATE INDEX ix_horarios_generados_grupo_id ON horarios_generados (grupo_id)"))

    print("Migracion completada: horarios_generados ahora usa llaves foraneas.")


if __name__ == "__main__":
    main()
